name: LibraryCurrents
favicon: null
layout_spectrum: 0.41636325628496706
typography_spectrum: 0.26147111505270004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7628081652801484
  lightness: 0.7561064758338034
  saturation: 0.49222134961746633
  rhythmicContrast: 0.5106655217241496
purpose: []
